### ISSUE TITLE
Choosing an appropriate license

### ISSUE THREAD

**Issue by leehosung** [leehosung/writing_sandbox#22]
Nasol and me discussed about what we want for the licensing.
We want to open source code and contents as much as we can. I will compare some licenses and choose an appropriate license.

**Comment by nassol** [comment]
@leehosung Thanks!

**Comment by nassol** [comment]
/We `want to` open source `code and contents` as much as we can.

//We `decided to` opensource `the` code and `the` contents as much as we can. 

///It's not wrong to say `wan't to` but I'd rather choose `decided to` because we made a decision definitively. Also I'd use `the` for `code and contents`, since they imply code and contents `that we are going to create`.

**Comment by nassol** [comment]
@leehosung Do you think `/, //, ///` are also appropriate for the feedback formatting rule?

**Comment by leehosung** [comment]
This project follows MIT license.
